Caja/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('apertura/', views.apertura_view , name='apertura' ),
    path('cierre/', views.cierre_view, name='cierre'),
    path('panel_dinero/',views.panel_dinero, name='panel_dinero'),
    path('agregar_dinero/', views.agregar_dinero, name='agregar_dinero'),
    path('datos_caja/',views.datos_caja,name="datos_caja")
]

Gastos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('gasto_panel/',views.gasto_panel, name='gasto_panel'),
    path('agregar_gasto/', views.agregar_gasto, name='agregar_gasto')
]

Matrix/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler400, handler403 ,handler404,handler500
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Empleados.urls')),
    path('menu/',views.menu, name="menu"),
    path('', include('Caja.urls')),
    path('',include('Ventas.urls')),
    path('', include('Compras.urls')),
    path('', include('Proveedores.urls')),
    path('', include('Productos.urls')),
    path('', include('Gastos.urls')),
    path('panel_historial/',views.panel_historial, name="panel_historial"),
    path('historial_compras/', views.historial_compras,name='historial_compras'),
    path('ver_detalle_compra/<int:id_compras>/',views.ver_detalle_compra, name='ver_detalle_compra'),
    path('historial_ventas/', views.historial_ventas,name='historial_ventas'),
    path('ver_detalle_ventas/<int:id_ventas>/',views.ver_detalle_venta, name='ver_detalle_venta'),
    path('historial_gastos/', views.historial_gastos,name='historial_gastos'),   
    path('historial_ingresos_egresos/', views.historial_ingresos_egresos,name='historial_ingresos_egresos'),    
]
if settings.DEBUG is False:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler400 = 'Matrix.views.error_400'  
handler403 = 'Matrix.views.error_403'  
handler404 = 'Matrix.views.error_404'  
handler500 = 'Matrix.views.error_500'  

Ventas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('panel_venta/', views.panel_venta, name='panel_venta'),
    path('agregar_producto/<int:id_producto>/', views.agregar_producto, name='agregar_producto'),
    path('eliminar_producto_venta/<int:id_producto>/', views.eliminar_producto_venta, name='eliminar_producto_venta'),
    path('crear_factura/', views.crear_factura, name='crear_factura'),
    path('grafico_ventas/',views.grafico_ventas,name='grafico_ventas'),
    path('cancelar_venta', views.cancelar_venta, name='cancelar_venta')
]

Compras/models.py
from django.db import models
from Productos.models import Producto
from Proveedores.models import Proveedor
from datetime import datetime
from Caja.models import Caja  
from Empleados.models import Empleado
from django.core.validators import MinValueValidator

Metodos_Pagos = [('', ''), ('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'),
                 ('Tarjeta_de_Debito', 'Tarjeta de Debito')]

class Compra(models.Model):
    fecha_compra = models.DateTimeField(default=datetime.now)
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE, blank=True, null=True)
    productos = models.ManyToManyField(Producto, through='compra_intermedio')
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE, blank=True, null=True)
    total = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    metodo_pago = models.CharField(max_length=25, choices=Metodos_Pagos, default='', blank=True)
    id_sesion = models.CharField(max_length=20, default='')
    caja = models.ForeignKey(Caja, on_delete=models.CASCADE, related_name='compras', null=True)

    def __str__(self):
        return f"Compra de {self.total} - {self.metodo_pago} ({self.fecha_compra})"


class Compra_intermedio(models.Model):
    compra = models.ForeignKey(Compra, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    precio_de_compra = models.DecimalField(default=0, max_digits=10, decimal_places=2, validators=[MinValueValidator(0)],blank=False,null=False)
    cantidad = models.IntegerField(default=0,validators=[MinValueValidator(0)],blank=False,null=False)
    subtotal = models.DecimalField(default=0, max_digits=10, decimal_places=2)

Compras/forms.py
from .models import *
from django.forms import ModelForm

class Formulario_Proveedor(ModelForm):
    class Meta:
        model=Compra
        fields=['proveedor']

class Formulario_MetodoPago(ModelForm):
    class Meta:
        model=Compra
        fields=['metodo_pago']
        labels={'metodo_pago':'Método de pago'}
    
   

Gastos/forms.py
from django.forms import ModelForm
from .models import *
class Formulario_Gasto(ModelForm):
    class Meta:
        model = Gasto
        fields = ['descripcion_gasto','costo']

Proveedores/forms.py
from .models import *
from django.forms import ModelForm
class formulario_proveedor(ModelForm):
    class Meta:
        model= Proveedor
        fields= '__all__'

Compras/views.py
from django.shortcuts import render, redirect
from .models import *
from Productos.models import *
from Proveedores.models import *
from Empleados.models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.db.models import Sum,Count
from datetime import datetime, timedelta
from django.contrib import messages
from django.db.models.functions import ExtractMonth
from Caja.views import * 
from Caja.models import * 
from Gastos.models import Gasto
from django.contrib.auth.decorators import user_passes_test
from Empleados.views import *
@login_required
def panel_compras(request):
    id_proveedor = request.session.get('id_proveedor', None)
    id_compra = request.session.get('id_compra', None)
    
    if not Compra.objects.exists():
        request.session.pop('id_compra', None)
    
    if id_proveedor:
        proveedor = Proveedor.objects.get(id=id_proveedor)
        formulario_proveedor = Formulario_Proveedor({'proveedor': id_proveedor})
        lista_productos_proveedor = Producto_Intermedia.objects.filter(proveedor=proveedor)
        contexto = {
            'formulario_proveedor': formulario_proveedor,
            'lista_productos_proveedor': lista_productos_proveedor,
            'proveedor': proveedor  
        }
    else:
        formulario_proveedor = Formulario_Proveedor()
        contexto = {'formulario_proveedor': formulario_proveedor}
    
    formulario_metodo_pago = Formulario_MetodoPago()
    contexto.update({'formulario_metodo_pago': formulario_metodo_pago})
    
    if id_compra:
        compra = Compra.objects.get(id=id_compra)  
        lista_compra = compra.compra_intermedio_set.all()
        if lista_compra:
            total_compra = sum(producto.precio_de_compra * producto.cantidad for producto in lista_compra)
            compra.total = total_compra
            compra.save()
            subtotal = total_compra
            contexto.update({'compra': compra, 'lista_compra': lista_compra, 'subtotal': subtotal})
        else: 
            compra.delete() 
            request.session.pop('id_compra', None)
    
    return render(request, 'compras.html', contexto)

@login_required
def cancelar_compra(request):
    id_compra = request.session.get('id_compra', None)
    if id_compra:
        try:
            compra = Compra.objects.get(id=id_compra)
            compra.compra_intermedio_set.all().delete()
            compra.delete()
            request.session.pop('id_compra', None)
            request.session.pop('id_proveedor', None)
            messages.success(request, "Compra cancelada exitosamente.")
        except Compra.DoesNotExist:
            messages.error(request, "No se encontró la compra a cancelar.")
    return redirect('panel_compras')
def seleccionar_proveedor(request):
    if request.method == 'POST':
        proveedor_seleccionado = Formulario_Proveedor(request.POST)
        if proveedor_seleccionado.is_valid():
            id_proveedor = proveedor_seleccionado.instance.proveedor.id
            request.session['id_proveedor'] = id_proveedor
            id_compra = request.session.get('id_compra', None)
            if id_compra:
                try:
                    compra = Compra.objects.get(id=id_compra)
                    compra.proveedor = proveedor_seleccionado.instance.proveedor
                    compra.save()
                except Compra.DoesNotExist:
                    pass  
            return redirect('panel_compras')

@login_required
def agregar_producto_compra(request, id_producto):
    producto = Producto.objects.get(id=id_producto)
    id_compra = request.session.get('id_compra', None)    
    caja_abierta = obtener_caja_abierta(request.user)

    if not caja_abierta:
        request.session['caja_abierta'] = False
        return redirect('apertura')
    
    id_sesion = request.session.session_key
    lista_ventas = Venta.objects.filter(id_sesion=id_sesion)
    total_ventas = sum(venta.total_venta for venta in lista_ventas)

    lista_compras = Compra.objects.filter(id_sesion=id_sesion)
    total_compras = sum(compra.total for compra in lista_compras)
    
    lista_dinero = Dinero.objects.filter(id_sesion=id_sesion)
    dinero_ingreso = sum(dinero.ing_egre for dinero in lista_dinero if dinero.tipo_dinero == 'Ingreso')
    dinero_egreso = sum(dinero.ing_egre for dinero in lista_dinero if dinero.tipo_dinero == 'Egreso')
    
    lista_gastos= Gasto.objects.filter(id_sesion= id_sesion)
    gastos_compra= sum(gasto.costo for gasto in lista_gastos)
    
    saldo_final = total_ventas + caja_abierta.saldo_inicial -total_compras+dinero_ingreso- dinero_egreso-gastos_compra
    if id_compra:
        try:
            compra = Compra.objects.get(id=id_compra)
        except Compra.DoesNotExist:
            compra = Compra()
            proveedor = Proveedor.objects.get(id=request.session.get('id_proveedor'))
            compra.proveedor = proveedor
            compra.save()
    else:
        compra = Compra()
        id_proveedor = request.session.get('id_proveedor', None)
        proveedor = Proveedor.objects.get(id=id_proveedor)
        compra.proveedor = proveedor
        compra.save()
        request.session['id_compra'] = compra.id

    if request.method == 'POST':
        precio_compra = int(request.POST.get('precio_compra'))
        cantidad = int(request.POST.get('cantidad'))
        subtotal_nuevo_producto = precio_compra * cantidad
        total_compra_actual = sum(p.precio_de_compra * p.cantidad for p in compra.compra_intermedio_set.all())
        if total_compra_actual + subtotal_nuevo_producto > saldo_final:
            messages.error(request, f'Saldo insuficiente. Saldo disponible: ${saldo_final}')
            return redirect('panel_compras')        
        producto_a_comprar, created = compra.compra_intermedio_set.get_or_create(producto=producto)
        producto_a_comprar.cantidad += cantidad
        producto_a_comprar.precio_de_compra = precio_compra
        producto_a_comprar.subtotal = producto_a_comprar.cantidad * producto_a_comprar.precio_de_compra
        producto_a_comprar.save()
        total_compra = sum(p.precio_de_compra * p.cantidad for p in compra.compra_intermedio_set.all())
        compra.total = total_compra
        compra.save()
    return redirect('panel_compras')

def eliminar_producto_compra(request, id_producto):
    if request.method=='POST':
        id_compra = request.session.get('id_compra')
        compra = Compra.objects.get(id=id_compra)
        producto_a_eliminar = Compra_intermedio.objects.get(compra_id=id_compra, producto_id=id_producto)
        producto_a_eliminar.delete()
        return redirect('panel_compras')


def confirmar_compra(request):
    if request.method == 'POST':
        compra = Compra.objects.get(id=request.session.get('id_compra'))
        formulario_metodo_pago = Formulario_MetodoPago(request.POST, instance=compra)
        if formulario_metodo_pago.is_valid():
            formulario_metodo_pago.save()
            compra.empleado = Empleado.objects.get(username=request.user.username)
            compra.id_sesion = request.session.session_key
            compra.save()
            request.session.pop('id_compra')
            request.session.pop('id_proveedor')
        
        lista_productos_comprados = compra.compra_intermedio_set.all()
        for producto_comprado in lista_productos_comprados:
            producto = Producto.objects.get(id=producto_comprado.producto.id)
            producto.existencias += producto_comprado.cantidad
            producto.save()
        return redirect('panel_compras')


@user_passes_test(is_admin)
def grafico_compras(request):
    fecha_inicio = request.GET.get('fecha_inicio')
    fecha_fin = request.GET.get('fecha_fin')
    mes = request.GET.get('mes')
    anio = request.GET.get('anio')
    current_year = datetime.now().year

    meses = Compra.objects.annotate(mes=ExtractMonth('fecha_compra')).values_list('mes', flat=True).distinct().order_by('mes')
    anios = list(range(current_year - 10, current_year + 1))

    total_efectivo = 0
    total_transferencia = 0
    total_tarjeta_debito = 0
    periodo = []

    if 'filtro' in request.GET:
        filtro = request.GET.get('filtro')

        if filtro == 'fechas':
            if not fecha_inicio or not fecha_fin:
                messages.error(request, 'Debe seleccionar un rango de fechas válido.')
            else:
                fecha_inicio = datetime.strptime(fecha_inicio, '%Y-%m-%d')
                fecha_fin = datetime.strptime(fecha_fin, '%Y-%m-%d')
                if fecha_inicio > fecha_fin:
                    fecha_inicio, fecha_fin = fecha_fin, fecha_inicio
                    messages.info(request, "Fechas invertidas para poder realizar la búsqueda.")
                periodo = [(fecha_inicio + timedelta(days=x)).strftime('%Y-%m-%d') for x in range((fecha_fin - fecha_inicio).days + 1)]
                compras = Compra.objects.filter(fecha_compra__range=[fecha_inicio, fecha_fin])
                total_efectivo = int(compras.filter(metodo_pago='Efectivo').aggregate(total=Sum('total'))['total'] or 0)
                total_transferencia = int(compras.filter(metodo_pago='Transferencia').aggregate(total=Sum('total'))['total'] or 0)
                total_tarjeta_debito = int(compras.filter(metodo_pago='Tarjeta_de_Debito').aggregate(total=Sum('total'))['total'] or 0)

        elif filtro == 'mes':
            if not mes:
                messages.error(request, 'Debe seleccionar un mes.')
            else:
                mes = int(mes)
                anio = int(current_year)
                periodo = [f"{anio}-{mes:02d}"]
                compras = Compra.objects.filter(fecha_compra__year=anio, fecha_compra__month=mes)
                total_efectivo = int(compras.filter(metodo_pago='Efectivo').aggregate(total=Sum('total'))['total'] or 0)

Gastos/views.py
from django.shortcuts import render,redirect
from .models import *
from Empleados import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from Ventas.models import Venta
from Compras.models import Compra
from Caja.models import * 
from Caja.views import *
@login_required
def gasto_panel(request):
    caja_abierta = Caja.objects.filter(empleado=request.user, estado='Abierta').first()
    if caja_abierta:
        formulario=Formulario_Gasto()
        lista_gasto=Gasto.objects.filter(id_sesion=request.session.session_key)
        return render(request, 'gasto.html', {'formulario':formulario, 'lista_gasto':lista_gasto})
    else:
        return redirect('apertura')
@login_required
def agregar_gasto(request):
    if request.method == 'POST':
        caja_abierta= obtener_caja_abierta(request.user)
        formulario = Formulario_Gasto(request.POST)        
        if formulario.is_valid():
            id_sesion = request.session.session_key
            lista_ventas = Venta.objects.filter(id_sesion=id_sesion)
            total_ventas = sum(venta.total_venta for venta in lista_ventas)

            lista_compras = Compra.objects.filter(id_sesion=id_sesion)
            total_compras = sum(compra.total for compra in lista_compras)

            lista_dinero = Dinero.objects.filter(id_sesion=id_sesion)
            dinero_ingreso = sum(dinero.ing_egre for dinero in lista_dinero if dinero.tipo_dinero == 'Ingreso')
            dinero_egreso = sum(dinero.ing_egre for dinero in lista_dinero if dinero.tipo_dinero == 'Egreso')
            
            lista_gastos= Gasto.objects.filter(id_sesion=id_sesion)
            gastos_compra= sum(gasto.costo for gasto in lista_gastos)

            saldo_final= caja_abierta.saldo_inicial+total_ventas-total_compras+dinero_ingreso- dinero_egreso-gastos_compra
            monto_ingresado = formulario.cleaned_data.get('costo')
            if monto_ingresado is None or saldo_final is None:
                messages.error(request, 'Error al obtener los valores de saldo o monto ingresado.')
                return redirect('gasto_panel')

            if saldo_final < monto_ingresado:
                messages.error(request, f'Saldo insuficiente. Saldo disponible: ${saldo_final:.2f}')
                return redirect('gasto_panel')
            formulario.instance.id_sesion = request.session.session_key
            formulario.instance.empleado = Empleado.objects.get(username=request.user.username)
            formulario.save()

    return redirect('gasto_panel')

templates/cambiar_contraseña.html
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h2 class="modal-title">Cambiar Contraseña</h2>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form method="POST" action="{% url 'cambiar_clave' id_empleado=id_empleado %}">
                {% csrf_token %}
                <div class="mb-3 position-relative">
                    <label for="new_password" class="form-label">Nueva Contraseña</label>
                    <input type="password" name="password" class="form-control" id="new_password" required>
                    <i id="new_password_icon" class="bi bi-eye-slash-fill position-absolute top-50 end-0 me-3" onclick="togglePassword('new_password', 'new_password_icon')" style="right: 10px; top: 45%; cursor: pointer; font-size:25;"></i>
                </div>
                <div class="mb-3 position-relative">
                    <label for="password_confirm" class="form-label">Confirmar Contraseña</label>
                    <input type="password" name="password_confirm" class="form-control" id="password_confirm" required>
                    <i id="password_confirm_icon" class="bi bi-eye-slash-fill position-absolute top-50 end-0 me-3" onclick="togglePassword('password_confirm', 'password_confirm_icon')" style="right: 10px; top: 45%; cursor: pointer; font-size:25;"></i>
                </div>
                <div class="d-flex justify-content-between">
                    <button type="submit" class="btn btn-primary" id="btn-cambiar">Guardar</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                </div>
            </form>
        </div>
    </div>
</div>

templates/factura.html
{% extends 'menu.html' %}
{% load static %}

{% block title %}Ticket{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/factura.css' %}">
{% endblock %}
{% block content %}
    <div class="container mt-5">
        <div class="card p-4">
            <h1 class="text-center">Ticket N° {{ venta.id }}</h1>
            <div class="text-center">
                <img src="{% static 'IMAGENES/logoOficialMatrix.png' %}" alt="logo-matrix" class="img-fluid mb-3" style="max-width: 200px;">
            </div>
            <p class="text-center">Dirección: Calle Los Delfines nº 270 casa nº 11</p>
            <p class="text-center">WhatsApp: 3875814670</p>
            <p class="text-center">Email: matrixmotos_saltacapital@gmail.com</p>
            <p class="text-center">Seguinos en @matrix_repuestosmot</p>
            <p class="text-center">Fecha: {{ venta.fecha|date:"d/m/Y" }} Hora: {{ venta.fecha|time:"H:i" }}</p>
            <p class="text-center">Método de Pago: {{ venta.get_metodo_pago_display }}</p>
            <table class="table table-bordered mt-3">
                <thead class="table-dark">
                    <tr>
                        <th>Nombre</th>
                        <th>Precio Unitario</th>
                        <th>Cantidad</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for producto in productos_a_vender %}
                    <tr>
                        <td>{{ producto.producto.nombre }}</td>
                        <td>${{ producto.producto.precio }}</td>
                        <td>{{ producto.cantidad }}</td>
                        <td>${{ producto.subtotal }}</td>
                    </tr>
                    {% endfor %}
                    <tr class="table-secondary">
                        <td colspan="3" class="text-end fw-bold">Total</td>
                        <td>${{ venta.total_venta }}</td>
                    </tr>
                </tbody>
            </table>
            <br>
            <p class="text-center">Gracias por su compra. Lo esperamos nuevamente.</p>
            <div class="text-center">
                <button class="btn btn-primary" onclick="window.location.href='{% url 'panel_venta' %}'">Nueva Venta</button>
            </div>
        </div>
    </div>
{% endblock %}

templates/historial_compras.html
{% extends 'menu.html' %}
{% load static %}

{% block title %} Historial de Compras{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/historial_compras.css' %}">
{% endblock %}
{% block content %}
    <div class="contenedor card">
        <h2>HISTORIAL DE COMPRAS</h2>
        <table class="table table-bordered table-hover">
            <tr class="table-dark">
                <th>ID Compra</th>
                <th>Empleado</th>
                <th>Fecha</th>
                <th>Método de Pago</th>
                <th>Total</th>
                <th>Productos</th>
            </tr>
            <tbody class="table-secondary">
                {% for compra in historial_compras %}
                    <tr>
                        <td>{{compra.id}}</td>
                        <td>{{compra.empleado.username}}</td>
                        <td>{{compra.fecha_compra}}</td>
                        <td>{{compra.get_metodo_pago_display}}</td>
                        <td>${{compra.total}}</td>
                        <td>
                            <a href="javascript:void(0);" onclick="modal_detalle('{% url 'ver_detalle_compra' compra.id %}')">Ver Productos</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="modal fade" id="detalleCompraModal" tabindex="-1" role="dialog" aria-labelledby="detalleCompraModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h2 class="modal-title" id="detalleCompraModalLabel">Detalle de la Compra</h2>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
                    </div>
                    <div class="modal-body" id="detalleCompraBody">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="d-flex justify-content-center mt-4">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1" aria-label="Primera">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">anterior</a>
                        </li>
                    {% endif %}
                    <li class="page-item disabled">
                        <span class="page-link">Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</span>
                    </li>
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">siguiente</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Última">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>

<script>
    function modal_detalle(url) {
        fetch(url)
            .then(response => response.text())
            .then(data => {
                document.getElementById('detalleCompraBody').innerHTML = data; 
                var myModal = new bootstrap.Modal(document.getElementById('detalleCompraModal')); 
                myModal.show();
            })
            .catch(error => console.error('Error:', error));
    }
</script>

{% endblock %}

templates/historial_ventas.html
{% extends 'menu.html' %}
{% load static %}

{% block title %} Historial de Ventas{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/historial_ventas.css' %}">
{% endblock %}
{% block content %}
    <div class="contenedor card">
        <h2>HISTORIAL DE VENTAS</h2>
        <table class="table table-bordered table-hover">
            <tr class="table-dark">
                <th>ID Venta</th>
                <th>Empleado</th>
                <th>Fecha</th>
                <th>Método de Pago</th>
                <th>Total</th>
                <th>Productos Vendidos</th>
            </tr>
            <tbody>
                {% for venta in historial_ventas %}
                    <tr>
                        <td>{{ venta.id }}</td>
                        <td>{{ venta.empleado.username }}</td>
                        <td>{{ venta.fecha }}</td>
                        <td>{{ venta.get_metodo_pago_display }}</td>
                        <td>${{ venta.total_venta }}</td>
                        <td>
                            <a href="javascript:void(0);" onclick="modal_detalle_venta('{% url 'ver_detalle_venta' venta.id %}')">Ver detalle</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="modal fade" id="detalleVentaModal" tabindex="-1" role="dialog" aria-labelledby="detalleVentaLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h2 class="modal-title" id="detalleVentaLabel">Detalle de la Venta</h2>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
                    </div>
                    <div class="modal-body">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="d-flex justify-content-center mt-4">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1" aria-label="Primera">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">anterior</a>
                        </li>
                    {% endif %}
                    <li class="page-item disabled">
                        <span class="page-link">Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</span>
                    </li>
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">siguiente</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Última">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>

    <script>
        function modal_detalle_venta(url) {
            fetch(url)
                .then(response => response.text())
                .then(data => {
                    document.getElementById('detalleVentaModal').querySelector('.modal-body').innerHTML = data;
                    var myModal = new bootstrap.Modal(document.getElementById('detalleVentaModal'));
                    myModal.show();
                })
                .catch(error => console.error('Error:', error));
        }
    </script>

{% endblock %}